version: "3"
services:
  web:
    # http://localhost:80
    image: ${REGISTRY_NAME}demo42/web:${TAG}
    build:
      context: ../web/
      dockerfile: ./src/WebUI/Dockerfile
    ports:
      - "80:80"
    environment:
      - QuotesUri=http://quotes-api/
    networks:
      - webnet
  quotes-api:
    # http://localhost:8080/quotes/rand
    image: ${REGISTRY_NAME}demo42/quotes-api:${TAG}
    build:
      context: ../quotes/
      dockerfile: ./src/QuoteService/Dockerfile
    environment:
      - ConnectionString=$DBCONNECTIONSTRING
    ports:
      - "8080:80"
    networks:
      - webnet
networks:
  webnet: