apiVersion: v1beta2
replicaCount: 1

web:
  image: demo42/web:vn

api:
  image: demo42/quotes-api:vn

quotes-api-db-connectionstring: myconnectionNotStringed

imageCredentials:
  registry: registry
  username: username
  password: password