apiVersion: v1
kind: Secret
metadata:
  name: app-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quotes-api-db-connectionstring
type: Opaque
data:
  db-connectionstring: {{ .Values.dbConnectionString | b64enc | quote }}