apiVersion: v1
kind: Secret
metadata:
  name: app-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quotes-api-db-connectionstring
type: Opaque
data:
  ConnectionString: {{ .Values.ConnectionString | b64enc | quote }}