apiVersion: v1beta2
replicaCount: 1

web:
  image: demo42/web:vn
  replicas: 1

api:
  image: demo42/quotes-api:vn
  replicas: 1

quotes-api-db-connectionstring: myconnectionNotStringed

imageCredentials:
  registry: registry
  username: username
  password: password