apiVersion: v1beta2
replicaCount: 1

web:
  image: demo42/web:vn
  replicas: 4
quotes-api:
  image: demo42/quotes-api:vn
  replicas: 2

queueworker:
  image: demo42/queueworker:vn
  replicas: 2
quotes-api-db-connectionstring: myconnectionNotStringed

imageCredentials:
  registry: registry
  username: username
  password: password